<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class mata_kuliah extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $mata_kuliahs = [
            [
                'kode' => 'PAIK6501',
                'nama' => 'Pengembangan Berbasis Platform - A',
                'sks' => 4,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '10:00:00',
            ],
            [
                'kode' => 'PAIK6501',
                'nama' => 'Pengembangan Berbasis Platform - B',
                'sks' => 4,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
            ],
            [
                'kode' => 'PAIK6501',
                'nama' => 'Pengembangan Berbasis Platform - C',
                'sks' => 4,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '10:00:00',
            ],
            [
                'kode' => 'PAIK6501',
                'nama' => 'Pengembangan Berbasis Platform - D',
                'sks' => 4,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
            ],
            [
                'kode' => 'PAIK6502',
                'nama' => 'Komputasi Tersebar dan Pararel - A',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '10:30:00',
                'jam_selesai' => '13:00:00',
            ],
            [
                'kode' => 'PAIK6502',
                'nama' => 'Komputasi Tersebar dan Pararel - B',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6502',
                'nama' => 'Komputasi Tersebar dan Pararel - C',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '10:30:00',
                'jam_selesai' => '13:00:00',
            ],
            [
                'kode' => 'PAIK6502',
                'nama' => 'Komputasi Tersebar dan Pararel - D',
                'sks' => 3,
                'semester' => 3,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6503',
                'nama' => 'Sistem Informasi - A',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '15:30:00',
                'jam_selesai' => '18:00:00',
            ],
            [
                'kode' => 'PAIK6503',
                'nama' => 'Sistem Informasi - B',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Senin',
                'jam_mulai' => '13:30:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6503',
                'nama' => 'Sistem Informasi - C',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '13:30:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6503',
                'nama' => 'Sistem Informasi - D',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '15:30:00',
                'jam_selesai' => '18:00:00',
            ],
            [
                'kode' => 'PAIK6504',
                'nama' => 'Proyek Perangkat Lunak - A',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6504',
                'nama' => 'Proyek Perangkat Lunak - B',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6504',
                'nama' => 'Proyek Perangkat Lunak - C',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6504',
                'nama' => 'Proyek Perangkat Lunak - D',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6505',
                'nama' => 'Pembelajaran Mesin - A',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6505',
                'nama' => 'Pembelajaran Mesin - B',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6505',
                'nama' => 'Pembelajaran Mesin - C',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6505',
                'nama' => 'Pembelajaran Mesin - D',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6506',
                'nama' => 'Keamanan dan Jaminan Informasi - A',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6506',
                'nama' => 'Keamanan dan Jaminan Informasi - B',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6506',
                'nama' => 'Keamanan dan Jaminan Informasi - C',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Jumat',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'PAIK6506',
                'nama' => 'Keamanan dan Jaminan Informasi - D',
                'sks' => 3,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Jumat',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'UUW00008',
                'nama' => 'Kewirausahaan - A',
                'sks' => 2,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Jumat',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '11:30:00',
            ],
            [
                'kode' => 'UUW00008',
                'nama' => 'Kewirausahaan - B',
                'sks' => 2,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Jumat',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '14:30:00',
            ],
            [
                'kode' => 'UUW00008',
                'nama' => 'Kewirausahaan - C',
                'sks' => 2,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
            ],
            [
                'kode' => 'UUW00008',
                'nama' => 'Kewirausahaan - D',
                'sks' => 2,
                'semester' => 5,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '14:30:00',
            ],
            [
                'kode' => 'PAIK6702',
                'nama' => 'Teori Bahasa dan Otomata - A',
                'sks' => 3,
                'semester' => 7,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6702',
                'nama' => 'Teori Bahasa dan Otomata - B',
                'sks' => 3,
                'semester' => 7,
                'prodi' => 'Informatika',
                'hari' => 'Kamis',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ],
            [
                'kode' => 'PAIK6702',
                'nama' => 'Teori Bahasa dan Otomata - C',
                'sks' => 3,
                'semester' => 7,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
            ],
            [
                'kode' => 'PAIK6702',
                'nama' => 'Teori Bahasa dan Otomata - C',
                'sks' => 3,
                'semester' => 7,
                'prodi' => 'Informatika',
                'hari' => 'Rabu',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:30:00',
            ]
        ];

        DB::table('mata_kuliahs')->insert($mata_kuliahs);
    }
}